package com.yasik.model.graph;

public enum GraphType {
    CUSTOMER_WITH_AUTHORITIES_ADDRESSES_FEEDBACK_ORDERS,
    CUSTOMER_WITH_AUTHORITIES,
    CUSTOMER_WITH_ADDRESSES,
    PRODUCT_WITH_PICTURE_CATEGORY_FEEDBACK_ORDERS,
    PRODUCT_WITH_PICTURE_FEEDBACK,
    CATEGORY_WITH_PRODUCTS,
    PURE_ENTITY;
}
